name: htsget-compliance 

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install setuptools
        python -m pip install --upgrade pip
        python setup.py install
        python -m pip install -r requirements.txt
    - name: Run tests
      run: python -m pytest --cov=ga4gh/ --cov-report=term-missing unittests/
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm]
    needs: test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker GitHub release
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        tags: ghcr.io/ga4gh/htsget-compliance:latest
